### ISSUE TITLE
A question about the ablation study in section 5.4

### ISSUE THREAD

**Issue by ilingen** [yeonsw/RankEncoder#3]
Hi, Thanks for your excellent work!

After reading your paper, I have a question about the ablation model in section 5.4. For the ablation models where does the semantic vector of a sentence come from? Based on my opinion , I think that for model RankEnocder_promptBert,  the semantic vector is just the rank vector produced by rankencoder E_1, for model RankEncoder_promptBERT-retrain, the semantic vector is the vector produced by the encoder E_2. 
Is there any mismatch with your paper？

Hope for your reply!

**Comment by yeonsw** [comment]
Hi,

Yes, you are understanding correctly!

Thanks

**Comment by ilingen** [comment]
Thanks for your reply!
I am going to close this issue.
